# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @title samples the parameter
#' This function samples the VARS-parameter of a latent-threshold VAR using a single move algorithm.
#' @param my LHS of data
#' @param amX RHS of data
#' @param mPhi transition matrix for VAR-Parameters
#' @param vmu mean of transition matrix
#' @param mSig variance-covariance matrix for standard deviation of parameters
#' @param amG2inv a KxKxT array with the stochastic volatility
#' @param vd latent threshold
#' @param mbo old betas
#' @param stabletest Test if candidate draw is stable (currently not implemented)
#' @param Intercept whether the model contains an intercept or not.
#' @param nl number of lags
NULL

fSampLTBv <- function(my, amX, mPhi, vmu, mSig, amG2inv, vd, mbo, stabletest, Intercept, nl) {
    .Call(`_ltvar_fSampLTBv`, my, amX, mPhi, vmu, mSig, amG2inv, vd, mbo, stabletest, Intercept, nl)
}

#' @export
#' @title samples the parameters for the transition of VAR-parameters
#' @param mp VAR-parameters
#' @param mSig standard deviation of the paramters
#' @param mPhi matrix with the transition parameters
#' @param vmu vector with intercepts
#' @param vd vector with the thresholds
#' @param dk0 latent threshold prior
#' @param dnu prior on the volatility of parameters, scale of inverse gamma distribution
#' @param dV0 prior on the volatility of parameters, shape of inverse gamma distribution
#' @param da0 prior on Phi, shape of beta distribution (alpha)
#' @param db0 prior on Phi, shpae of beta distribution (beta)
#' @param dm0 Prior on Intercept, mean of normal distribution
#' @param ds0 Prior on Intercept, variance of normal distribution
NULL

fSampSPM <- function(mp, mSig, mPhi, vmu, dnu, dV0, da0, db0, dm0, ds0, vd, dk0) {
    .Call(`_ltvar_fSampSPM`, mp, mSig, mPhi, vmu, dnu, dV0, da0, db0, dm0, ds0, vd, dk0)
}

