# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @title samples
#' @param my LHS of data
#' @param mx RHS of data
#' @param mPhi transition matrix for VAR-Parameters

fSampLTBv <- function(my, amX, mPhi, vmu, mSig, amG2inv, vd, mbo, stabletest, Intercept, nl) {
    .Call('_ltvar_fSampLTBv', PACKAGE = 'ltvar', my, amX, mPhi, vmu, mSig, amG2inv, vd, mbo, stabletest, Intercept, nl)
}

fSampSPM <- function(mp, mSig, mPhi, vmu, dnu, dV0, da0, db0, dm0, ds0, vd, dk0) {
    .Call('_ltvar_fSampSPM', PACKAGE = 'ltvar', mp, mSig, mPhi, vmu, dnu, dV0, da0, db0, dm0, ds0, vd, dk0)
}

